version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_courseplanner
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: CoursePlanner
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql